### ISSUE TITLE
Product single page: There is no proper row alignment for the product thumbnails.  They don't have even size of containerss.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Starkeys#86]
![image](https://cloud.githubusercontent.com/assets/11186313/11733895/422f7248-9fed-11e5-8ec6-496fd1cb889d.png)
![image](https://cloud.githubusercontent.com/assets/11186313/11733926/93ae8d84-9fed-11e5-9d01-fd84c6a186fd.png)

**Comment by Santosh-titan** [comment]
Note: Hard crop has been removed for small thumbnail image because  of it images won't align with main image.See Attachment
http://starkeyproducts.stage.titanweb.com.au/products/cockroach-glue-board-traps/a-simple-product/
![screenshot-starkeyproducts stage titanweb com au 2015-12-11 10-58-27](https://cloud.githubusercontent.com/assets/13828562/11736634/783afb9c-9ff6-11e5-8efb-3f477649033d.png)
